# build environment
FROM node:10.20.1-alpine as builder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH
ENV SHELL=/bin/sh
COPY package.json /usr/src/app/package.json
RUN npm install --silent

#declare arguments
#ARG NODE_ENV
ARG VUE_APP_API_URL

# expose environment to the new container
#ENV NODE_ENV $NODE_ENV
ENV VUE_APP_API_URL $VUE_APP_API_URL

COPY . /usr/src/app
RUN npm run build

# production environment
FROM nginx:1.15.8-alpine
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]