version: '3.7'

services:

  nginx:
    container_name: nginx
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - server
    ports:
      - "80:80"
    volumes:
      - ./images/php/app/public:/var/www/html/app/public

  web:
    container_name: web
    build:
      context: ./images/vue
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - ./images/vue:/usr/src/app
    environment:
      - PUBLIC_URL=${DOMAIN}
      - REACT_APP_COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    networks:
      - frontend
    ports:
    - 8080:8080

  server:
    container_name: server
    build:
      context: ./images/php
      dockerfile: Dockerfile
    volumes:
      - /var/www/html/app/vendor
      - ./images/php/app:/var/www/html/app
    links:
      - db
      - cache
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
    networks:
      - backend

  db:
    container_name: db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend

  cache:
    image: memcached:1.6-alpine
    networks:
      - backend

networks:
  frontend:
  backend: