version: '3.7'

services:

  nginx:
    container_name: nginx
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - api
    ports:
      - "80:80"
    volumes:
      - ./images/php/app/public:/var/www/html/app/public
    networks:
      - frontend
      - backend

  web:
    container_name: web
    build:
      context: ./images/vue
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - ./images/vue:/usr/src/app
    environment:
      - PUBLIC_URL=${DOMAIN}
      - CHOKIDAR_USEPOLLING=true
      - VUE_APP_API_URL=${VUE_APP_API_URL}
    depends_on:
      - api
    networks:
      - frontend
    ports:
    - 8080:8080
    - 8000:8080
    - 8081:8081

  api:
    container_name: api
    build:
      context: ./images/php
      dockerfile: Dockerfile
    volumes:
      - /var/www/html/app/vendor
      - ./images/php/app:/var/www/html/app
    links:
      - db
      - cache
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
      PAYSTACK_SEC: ${PAYSTACK_SEC}
      PAYSTACK_PUB: ${PAYSTACK_PUB}
      CALLBACK_URL: ${CALLBACK_URL}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - backend

  db:
    container_name: db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend

  cache:
    image: memcached:1.6-alpine
    networks:
      - backend

networks:
  frontend:
  backend: